# Generated by Django 4.0.3 on 2022-03-21 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_info', models.CharField(max_length=100)),
                ('unique_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Emergency_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_check_in', models.CharField(max_length=100)),
                ('second_check_in', models.CharField(max_length=100)),
                ('final_warning', models.CharField(max_length=100)),
                ('dater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal_Info.dater')),
                ('emergency_contact', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Personal_Info.emergency_contact')),
            ],
        ),
        migrations.AddField(
            model_name='dater',
            name='emergency_contact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Personal_Info.emergency_contact'),
        ),
        migrations.AddField(
            model_name='dater',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
