# Generated by Django 4.0.3 on 2022-03-23 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_info', models.CharField(max_length=100)),
                ('unique_password', models.CharField(max_length=50)),
                ('emergency_contact', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact1', to='Personal_Info.dater')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default=None, max_length=200)),
                ('dater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dater1', to='Personal_Info.dater')),
                ('emergency_contact', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact2', to='Personal_Info.dater')),
            ],
        ),
    ]
