# Generated by Django 4.0.3 on 2022-03-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_Info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='final_warning',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='first_check_in',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='second_check_in',
        ),
        migrations.AddField(
            model_name='messages',
            name='message',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
