# Generated by Django 4.0.3 on 2022-03-23 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_Info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dater',
            name='emergency_contact',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact1', to='Personal_Info.dater'),
        ),
    ]
