# Generated by Django 4.0.3 on 2022-03-16 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Personal_Info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_info',
            old_name='model',
            new_name='eye_color',
        ),
        migrations.RenameField(
            model_name='personal_info',
            old_name='make',
            new_name='hair_color',
        ),
        migrations.RenameField(
            model_name='personal_info',
            old_name='year',
            new_name='height',
        ),
        migrations.AddField(
            model_name='personal_info',
            name='name',
            field=models.CharField(default='n', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_info',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_check_in', models.CharField(max_length=100)),
                ('second_check_in', models.CharField(max_length=100)),
                ('final_warning', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_info', models.CharField(max_length=100)),
                ('unique_password', models.CharField(max_length=50)),
                ('messages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal_Info.messages')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal_Info.personal_info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
