# Generated by Django 4.0.3 on 2022-03-28 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_Info', '0004_dater_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
