# Generated by Django 4.0.3 on 2022-03-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_Info', '0005_messages_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='latitude',
            field=models.IntegerField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='messages',
            name='longitude',
            field=models.IntegerField(default=None, max_length=100),
        ),
    ]
